### ISSUE TITLE
Getting an error with Hetzner/Host Europe SPF for domain "reichelt.de"

### ISSUE THREAD

**Issue by glowf1sh** [cite/spf_whitelist#1]
Hi there,

I love your script, but recently i´m getting this error. Could that be resolved via the code ?

`mta01 postfix/postscreen[97357]: warning: cidr map /etc/postfix/postscreen_whitelist, line 764: bad address pattern: "80.237.132.81-all": skipping this rule`

after trial and error with like 30 domains i found out by uncommenting each one, that this wrong format comes from reichelt.de

Any idea what could be done?

Thank you :)

**Comment by cite** [comment]
Well, there is a syntax error in their DNS entries:

```bash
$ dig reichelt.de txt +short
"MS=F9ECFB1C562C4103BACD4562ECCC57BBE3B98367"
"v=spf1 mx ip4:212.184.1.254 ip4:212.184.1.54 ip4:212.184.1.55 ip4:212.184.1.157 ip4:212.184.1.92 ip4:212.184.1.93 ip4:80.237.132.81-all"
```

As you can see, there's a space missing between `-all` and `ip4:80.237.132.81`. You might want to poke them about that ;-)

I'll try to add a check to the code that will skip faulty records.
